# Generated by Django 2.2.10 on 2021-08-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20210827_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='Emails',
            new_name='emails',
        ),
    ]
